ifdef::env-github[]
:tip-caption: :bulb:
:note-caption: :information_source:
:important-caption: :heavy_exclamation_mark:
:caution-caption: :fire:
:warning-caption: :warning:
endif::[]
:toc:
:toc-placement!:

= midPoint SOAP overlay example (code-first)

toc::[]

Example of a midPoint WAR overlay project that implements a custom SOAP web service.
It is based on midPoint 4.2.

The service is implemented by `ExampleSoapService` class without separate interface, so it is code-first approach with minimal ceremony with WSDL generated by CXF on the fly.
All necessary Spring configuration is in the `ctx-overlay.xml` configuration file.
Name of the file is important, midPoint searches for the files with this name on the classpath.

This is an alternative to the official https://github.com/Evolveum/midpoint-custom-service[SOAP overlay example]
with a couple of differences:

* This one is code-first single maven module.
The official one uses WSDL and two modules (separate module for the service and overlay building).
You can mix and match, both can be single or multi-module in their current form.
* This one uses REST channel's basic authentication.
The official one bypasses midPoint's flexible authentication and uses WS-Security from CXF.
Again, you can mix and match and use WS-Security with code-first approach.

== Building and running

To build the example run:

----
mvn package
----

The final `midpoint.war` will be built in `target`.

You can deploy the WAR to the Tomcat or preferably run it directly if `java` is on the path:

----
java -jar target/midpoint.war
----

To run in an IDE choose `com.evolveum.midpoint.web.boot.MidPointSpringApplication` as the main class.
Be sure to add "provided" scope to the classpath in the run configuration.

[WARNING]
If `midpoint.home` does not exist *run as JAR first*, not IDE, otherwise `initial-objects` loading fails.
If you made changes to the project, don't forget to `mvn clean package` it before running the JAR.

=== Testing

The service will be listening at http://localhost:8080/midpoint/ws/soap/example-1, to see WSDL use
http://localhost:8080/midpoint/ws/soap/example-1?wsdl.

[WARNING]
====
Do not use browser to access these URLs.
There seems to be a bug in basic authentication in midPoint that asks for credentials forever.
Using curl with "preemptive authentication" works fine.

You may ask: "Can't we just ignore the path with WSDL?"
The answer is no, because current ignore path matches paths without `?` part so there is no way
to distinguish WSDL requests from SOAP requests.
====

You can test the service with this command:

----
curl --user "administrator:5ecr3t" -d @- \
  -H "Content-Type: text/xml;charset=UTF-8" \
  http://localhost:8080/midpoint/ws/soap/example-1 <<< '
<soapenv:Envelope xmlns:soapenv="http://schemas.xmlsoap.org/soap/envelope/" xmlns:cus="http://midpoint.example.com/xml/ns/custom-soap-1">
   <soapenv:Header/>
   <soapenv:Body>
      <cus:self/>
   </soapenv:Body>
</soapenv:Envelope>
'
----

There is also search by user email (just like in https://github.com/Evolveum/midpoint-custom-service[original SOAP overlay example]):

----
curl --user "administrator:5ecr3t" -d @- \
  -H "Content-Type: text/xml;charset=UTF-8" \
  http://localhost:8080/midpoint/ws/soap/example-1 <<< '
<soapenv:Envelope xmlns:soapenv="http://schemas.xmlsoap.org/soap/envelope/" xmlns:cus="http://midpoint.example.com/xml/ns/custom-soap-1">
   <soapenv:Header/>
   <soapenv:Body>
      <cus:searchUserByEmail>
         <arg0>
            <email>jack@caribbean.com</email>
         </arg0>
      </cus:searchUserByEmail>
   </soapenv:Body>
</soapenv:Envelope>
'
----

See https://wiki.evolveum.com/display/midPoint/Customization+With+Overlay+Project[our overlay
documentation] for more details about midPoint overlay projects.
See https://github.com/Evolveum/midpoint-overlay-example[midpoint-overlay-example] for another simple overlay project (not WS specific).

=== Using SoapUI

SoapUI or similar tool makes it much easier to test SOAP web services as it is rather hard to construct the whole request XML manually.
But because of authentication it is not possible to just point to the WSDL (perhaps other tools can do it).
We need offline WSDL files - for convenience these are provided under `extractedWsdl` directory.

To get offline WSDL files after changes to the service, run these commands (with overlay running, of course):

----
curl --user "administrator:5ecr3t" http://localhost:8080/midpoint/ws/soap/example-1?wsdl |
  sed -e 's%http://localhost:8080/midpoint/ws/soap/example-1?wsdl=ExampleSoapService.wsdl%ExampleSoapService.wsdl%' \
  > example.wsdl
curl --user "administrator:5ecr3t" http://localhost:8080/midpoint/ws/soap/example-1?wsdl=ExampleSoapService.wsdl > ExampleSoapService.wsdl
----

Using `sed` will replace URL to imported second file with the local path to it.

Point SoapUI to the `example.wsdl` file and all should be fine.
Don't forget to https://www.soapui.org/docs/soap-and-wsdl/authenticating-soap-requests/[add basic
authentication] and also check *Pre-emptive auth*.

== Technical note about midPoint schema types

When using WSDL all the code is generated.
With code-first approach it is tempting to use existing types and let CXF to do its best (or what) to generate the WSDL.
Good advice - *always write your types separate from midPoint types.*
Especially midPoint "JAXB" `SomethingType` classes are not really JAXB compliant.
Using those as input/output types is a guaranteed way to obscure errors.
This example shows how to do it, you can even go with public fields if Sonar doesn't kill you for it.
